CAMERA_INDEX = 0
FRAME_WIDTH = 960
FRAME_HEIGHT = 540

EAR_THRESHOLD = 0.23
EAR_CONSEC_FRAMES = 15

MAR_THRESHOLD = 0.60
MAR_CONSEC_FRAMES = 10

YAWN_ALERT_COUNT = 3
YAWN_WINDOW_SECONDS = 60

ALERT_COOLDOWN_SECONDS = 3
SAVE_SNAPSHOTS = True
SNAPSHOT_DIR = "snapshots"
LOG_DIR = "logs"
LOG_FILE = "drowsiness_events.csv"

WINDOW_NAME = "VisionGuard Awake - Driver Drowsiness Monitor"
